luciancah/nextjs-ko

- package.json
- pages/_app.tsx
- pnpm-lock.yaml
VA monthly free quota 도달로 GA4로 이전합니다.
> [no-issue] feat: analytics provider 변경 (vercel -> GA4)

- pages/docs/pages/building-your-application/configuring/babel.mdx
**연관된 이슈 확인**
closes #13 
**기여 내용**
**문서 경로**
`/docs/pages/building-your-application/configuring/babel`
> [#13] building-your-application/configuring/babel 문서 번역

- pages/docs/pages/building-your-application/rendering/client-side-rendering.mdx
**연관된 이슈 확인**
closes #20 
**기여 내용**
**문서 경로**
`/docs/pages/building-your-application/rendering/client-side-rendering.mdx`
> [#20] docs: client-side-rendering 번역

- pages/docs/pages/building-your-application/rendering/server-side-rendering.mdx
**연관된 이슈 확인**
closes #22 
**기여 내용**
**문서 경로**
`e.g. /docs/pages/building-your-application/rendering/server-side-rendering`
> [#22] docs: server-side-rendering 번역

- .all-contributorsrc
- .prettierignore
- README.md
- package.json
- pages/_meta.json
- pages/docs/pages/building-your-application/configuring/babel.mdx
- pages/docs/pages/building-your-application/rendering/client-side-rendering.mdx
- pages/docs/pages/building-your-application/rendering/server-side-rendering.mdx
- pages/index.mdx
- public/sitemap.xml
- theme.config.tsx
🥰 기여 감사합니다!
- /pages/building-your-application/rendering/server-side-rendering
- /pages/building-your-application/rendering/client-side-rendering
- /pages/building-your-application/configuring/babel
**Vercel CI 옵션 변경**
```
git log -1 --pretty=oneline --abbrev-commit | grep -q "\[skip ci\]" && echo "🛑 Build skipped due to [skip deploy] tag" && exit 0 || echo "✅ Proceeding with build" && exit 1
```
> [#6] docs: 7월 4주차 문서 업데이트

- pages/docs/pages/building-your-application/configuring/debugging.mdx
**연관된 이슈 확인**
closes #32 
**기여 내용**
**문서 경로**
`docs/pages/building-your-application/configuring/debugging.mdx`
> [#32] building-your-application/configuring/debugging 문서 번역

- pages/docs/pages/building-your-application/configuring/error-handling.mdx
**연관된 이슈 확인**
closes #43
**기여 내용**
**문서 경로**
/docs/pages/building-your-application/configuring/error-handling.mdx
> docs: building-your-application/configuring/error-handling 번역

- pages/docs/pages/building-your-application/rendering/server-side-rendering.mdx
- pages/docs/pages/building-your-application/upgrading/version-13.mdx
**연관된 이슈 확인**
closes #46 
**기여 내용**
**문서 경로**
/docs/pages/building-your-application/upgrading/version-13
> [#46] docs: version-13 번역

- pages/docs/pages/building-your-application/data-fetching/client-side.mdx
**연관된 이슈 확인**
closes #15 
**기여 내용**
**문서 경로**
/docs/pages/building-your-application/data-fetching/client-side
> [#15] docs: client-side 번역

- pages/docs/pages/building-your-application/routing/custom-app.mdx
**연관된 이슈 확인**
closes #53
**기여 내용**
**문서 경로**
/docs/pages/building-your-application/routing/custom-app.mdx
> [#53] docs: custom-app.mdx 번역

- pages/docs/pages/building-your-application/upgrading/version-12.mdx
**연관된 이슈 확인**
closes #79 
**기여 내용**
**문서 경로**
docs/pages/building-your-application/upgrading/version-12.mdx
> [#79] docs: version-12 번역

- pages/docs/pages/building-your-application/configuring/preview-mode.mdx
**연관된 이슈 확인**
closes #56 
**기여 내용**
**문서 경로**
`/docs/pages/building-your-application/configuring/preview-mode.mdx`
> [#56] docs: preview-mode 번역

- pages/docs/pages/building-your-application/upgrading/version-10.mdx
- pages/docs/pages/building-your-application/upgrading/version-11.mdx
**연관된 이슈 확인**
closes #93 
closes #95
**기여 내용**
**문서 경로**
/docs/pages/building-your-application/upgrading/version-10.mdx
> [#93][#95] docs: version-10 & version-11 번역

- pages/docs/pages/building-your-application/rendering/automatic-static-optimization.mdx
**연관된 이슈 확인**
closes #81 
**기여 내용**
**문서 경로**
`/docs/pages/building-your-application/rendering/automatic-static-optimization.mdx`
> [#81] docs: automatic-static-optimization 번역

- pages/docs/pages/api-reference/functions/get-static-props.mdx
**연관된 이슈 확인**
closes #84 
**기여 내용**
**문서 경로**
> [#84] docs: getStaticProps 번역

- pages/docs/pages/building-your-application/routing/api-routes.mdx
**연관된 이슈 확인**
closes #109 
**기여 내용**
**문서 경로**
/docs/pages/building-your-application/routing/api-routes.mdx
> [#109] api-routes 번역

- pages/docs/pages/api-reference/functions/use-router.mdx
**연관된 이슈 확인**
closes #86 
**기여 내용**
**문서 경로**
/docs/pages/api-reference/functions/use-router.mdx
> [#86] docs: use-router.mdx 번역

- pages/docs/pages/building-your-application/routing/pages-and-layouts.mdx
**연관된 이슈 확인**
closes #111 
**기여 내용**
**문서 경로**
pages/docs/pages/building-your-application/routing/pages-and-layouts.mdx
> [#111] docs: pages-and-layouts 번역

- pages/docs/pages/building-your-application/routing/internationalization.mdx
**연관된 이슈 확인**
closes #87 
**기여 내용**
**문서 경로**
/docs/pages/building-your-application/routing/internationalization.mdx
> [#87] docs: internationalization 번역

- .all-contributorsrc
- README.md
- pages/docs/pages/api-reference/components/image-legacy.mdx
- pages/docs/pages/api-reference/functions/get-initial-props.mdx
- pages/docs/pages/api-reference/functions/get-static-props.mdx
- pages/docs/pages/api-reference/functions/use-router.mdx
- pages/docs/pages/building-your-application/configuring/amp.mdx
- pages/docs/pages/building-your-application/configuring/draft-mode.mdx
- pages/docs/pages/building-your-application/routing/api-routes.mdx
- pages/docs/pages/building-your-application/routing/internationalization.mdx
- pages/docs/pages/building-your-application/routing/pages-and-layouts.mdx
- pages/docs/pages/building-your-application/upgrading/version-9.mdx
- pages/index.mdx
🥰 기여 감사합니다!
- `/docs/pages/api-reference/functions/get-static-props.mdx` @grapefruit13 #106
- `/docs/pages/building-your-application/routing/api-routes.mdx` @kor-bim #110
- `/docs/pages/api-reference/functions/use-router.mdx` @WaterMinCho #113
- `/docs/pages/building-your-application/routing/pages-and-layouts.mdx` @jinlee0310 #114
- `/docs/pages/api-reference/components/image-legacy.mdx` @wlstmd #116
- `/docs/pages/building-your-application/configuring/draft-mode.mdx` @pySoo #117
- `/docs/pages/building-your-application/routing/internationalization.mdx` @davindev #118
- `/docs/pages/api-reference/functions/get-initial-props.mdx` @hyunmyungJaneLee #119
- `/docs/pages/building-your-application/upgrading/version-9.mdx` @mini-boo #101
- …
> [#6] docs: 8월 2주차 문서 업데이트

- pages/docs/pages/building-your-application/data-fetching.mdx
**연관된 이슈 확인**
closes #133 
**기여 내용**
**문서 경로**
`docs/pages/building-your-application/data-fetching`
> [#133] Docs : Data Fetching translation

- pages/docs/app/building-your-application/routing/parallel-routes.mdx
**기여 내용**
**문서 경로**
/docs/app/building-your-application/routing/parallel-routes
> [no-issue] fix: 잘못된 들여쓰기 수정
