.prettierignore
package.json
pnpm-lock.yaml
public/sitemap.xml
scripts/generate-sitemap.mjs

- nextra 프레임워크가 nextjs 13 Pages router 기반이라 nextjs api에 있는 기능 사용불가
- 정적페이지 기반 documentation이기 때문에 빌드시 정적파일 생성하는 방법으로 진행 (ssr 아님)

[no-issue] feat: seo 지연으로 사이트맵 추가

---

pages/docs/pages/building-your-application/data-fetching/get-static-paths.mdx

**연관된 이슈 확인**
closes #34
**기여 내용**
**문서 경로**
`/docs/pages/building-your-application/data-fetching/get-static-paths.mdx`

[#34] docs: get-static-paths 번역

---

pages/docs/pages/building-your-application/deploying/ci-build-caching.mdx

**연관된 이슈 확인**
closes #38 
**기여 내용**
**문서 경로**
`/docs/pages/building-your-application/deploying/ci-build-caching.mdx`

[#38] docs: ci-build-caching 번역

---

pages/docs/pages/building-your-application/routing/dynamic-routes.mdx

**연관된 이슈 확인**
closes #28
**기여 내용**
**문서 경로**
`/docs/pages/building-your-application/routing/dynamic-routes.mdx`

[#28] docs: dynamic-routes 번역

---

pages/docs/pages/building-your-application/data-fetching/get-static-props.mdx

**연관된 이슈 확인**
closes #26
**기여 내용**
**문서 경로**
`/docs/pages/building-your-application/data-fetching/get-static-props.mdx`

[#26] docs: get-static-props 번역

---

pages/docs/pages/building-your-application/data-fetching/get-server-side-props.mdx

**연관된 이슈 확인**
closes #29 
**기여 내용**
**문서 경로**
`/docs/pages/building-your-application/data-fetching/get-server-side-props.mdx`

[#29] docs: get-server-side-props 번역

---

pages/docs/pages/building-your-application/configuring/custom-server.mdx

**연관된 이슈 확인**
closes #57 
**기여 내용**
**문서 경로**
`/docs/pages/building-your-application/configuring/custom-server.mdx`

[#57] docs: custom server 번역

---

pages/docs/pages/building-your-application/routing/custom-document.mdx

**연관된 이슈 확인**
closes #73 
**기여 내용**
**문서 경로**
`/docs/pages/building-your-application/routing/custom-document.mdx`

[#73] docs: custom-document 번역

---

pages/docs/pages/api-reference/next-config-js/runtime-configuration.mdx

**연관된 이슈 확인**
closes #19 
**기여 내용**
**문서 경로**
pages/docs/pages/api-reference/next-config-js/runtime-configuration.mdx

[#19] docs: runtime-configurations 번역

---

pages/docs/pages/building-your-application/data-fetching/forms-and-mutations.mdx

**연관된 이슈 확인**
closes #17 
**기여 내용**
**문서 경로**

[#17] docs: forms-and-mutation 번역

---

pages/docs/pages/api-reference/functions/get-server-side-props.mdx
pages/docs/pages/building-your-application/rendering/server-side-rendering.mdx
pages/docs/pages/building-your-application/upgrading/version-13.mdx

**연관된 이슈 확인**
closes #77 (신규 문서 번역), #46 (문서 내 오타 수정)
**기여 내용**
**문서 경로**
/docs/pages/api-reference/functions/get-server-side-props

[#77] docs: get-server-side-prop 번역

---

pages/docs/pages/building-your-application/styling/css-modules.mdx

**연관된 이슈 확인**
closes #82
**기여 내용**
**문서 경로**
/docs/pages/building-your-application/styling/css-modules

[#82] docs: css-modules 번역

---

pages/docs/pages/building-your-application/routing/linking-and-navigating.mdx

**연관된 이슈 확인**
closes #33
**기여 내용**
**문서 경로**
/docs/pages/building-your-application/routing/linking-and-navigating.mdx

[#33] docs: linking-and-navigating 번역

---

pages/docs/pages/building-your-application/configuring/draft-mode.mdx

**연관된 이슈 확인**
closes #89 
**기여 내용**
**문서 경로**
`/docs/pages/building-your-application/configuring/draft-mode.mdx`

[#89] docs: draft-mode 번역

---

pages/docs/pages/api-reference/functions/get-initial-props.mdx

**연관된 이슈 확인**
closes #88
**기여 내용**
**문서 경로**
/docs/pages/api-reference/functions/get-initial-props.mdx

[#88] docs: getInitialProps 번역

---

pages/docs/pages/api-reference/components/head.mdx

**연관된 이슈 확인**
closes #124 
**기여 내용**
**문서 경로**
/docs/pages/api-reference/components/head

[#124] docs: head 번역

---

pages/docs/pages/api-reference/next-config-js/transpilePackages.mdx

**연관된 이슈 확인**
closes #131 
**기여 내용**
**문서 경로**
`/docs/pages/api-reference/next-config-js/transpilePackages`
**작업 내역**
pages 디렉토리에 누락된 transpilePackages 문서 추가

[#131] docs: transpilePackages 추가

---

.all-contributorsrc
README.md
pages/docs/pages/api-reference/components/head.mdx
pages/docs/pages/api-reference/next-config-js/transpilePackages.mdx
pages/docs/pages/building-your-application/data-fetching.mdx
pages/index.mdx

🥰 기여 감사합니다!
- `/docs/pages/api-reference/components/head.mdx` @harryseop #124 
- `docs/pages/building-your-application/data-fetching.mdx` @lionleeee #133 
- `/docs/pages/api-reference/next-config-js/transpilePackages.mdx` @sangseophwang #131

[no-issue] docs: 9월 1주차 문서 업데이트

---

pages/docs/app/building-your-application/routing/route-handlers.mdx

**기여 내용**
**문서 경로**
/docs/app/building-your-application/routing/route-handlers

[no-issue] fix: 일관성 및 잘못된 들여쓰기 수정

---

pages/docs/app/api-reference/functions/unstable_cache.mdx

**기여 내용**
**문서 경로**
/docs/app/api-reference/functions/unstable_cache

[no-issue] fix: 예시 코드 정리

---

components/externalImage.tsx

기존에 이미지가 정상적으로 출력되지 않던 문제를 해결하기 위해, ExternalImage 컴포넌트의 baseUrl을 변경했습니다.
기존 baseUrl은 'https://nextjs.org'였고, 새로운 baseUrl은 'https://h8DxKfmAPhn8O0p3.public.blob.vercel-storage.com'으로 수정했습니다.
- [✅] [기여 가이드](https://github.com/luciancah/nextjs-ko/blob/main/CONTRIBUTING.MD)를 확인한 후 작성 하셨나요?
- [✅] [용어집](https://github.com/luciancah/nextjs-ko/issues/18)을 확인한 후 작성 하셨나요? 번역하신 단어 중 용어집에 추가하고싶은 단어가 있으시다면 이슈에 댓글로 남겨주세요.
- [✅] title, description 등 마크다운 태그의 영문 원본 유지를 하셨나요?
- [✅] 소제목 (h1~h6, ### ... 등)의 영문 유지를 하셨나요?
- [✅] 문서의 전반적인 어조 톤과 일치하게 작성 하셨나요?
- [✅] 코드블록 내부의 주석이나 업데이트 로그 등 표 내부의 문자도 한국어로 번역 하셨나요?
**연관된 이슈 확인**
[no-issue]
**기여 내용**
- [✅ ] 기타 기능 개선 및 수정
**문서 경로**
/nextjs-ko/components/externalImage.tsx

[no-issue] fix: external image 컴포넌트의 baseUrl 수정
